title: Painting Dashbord
description: Using Python and Turtle modul 
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
